### ISSUE TITLE
Automatic API documentation generation

### ISSUE THREAD

**Issue by jamiebrynes7** [spatialos/gdk-for-unity#673]
**Summary**

Automatically generate and publish API documentation for all public & protected classes, structs, and interfaces on https://docs.improbable.io that matches our in-code documentation.

**Steps**

- [x] Implement API docs generator: https://github.com/spatialos/gdk-for-unity-shared-ci/pull/12
- [x] Ensure ToC can be nested "infinitely".
- [ ] Integrate into CI process.
- [x] Publish API docs.

**Unresolved Questions**

- [ ] Support for automatically documenting attributes
- [ ] Support for automatically documenting generic constraints
- [ ] How to handle custom CSS within Improbadoc 

Internal ticket references: [UTY-1485](https://improbableio.atlassian.net/browse/UTY-1485)

**Comment by jamiebrynes7** [comment]
API documentation has been published - process is semi-manual as documented in https://github.com/spatialos/gdk-for-unity/wiki/Release-Process

For the time being, the doc generator itself is sufficient. We can look at adding extra features in the future!
