### ISSUE TITLE
Unity 2018.3 support

### ISSUE THREAD

**Issue by jamiebrynes7** [spatialos/gdk-for-unity#676]
This issue tracks the progress of updating the GDK for Unity to work with 2018.3.xx

**Steps**

- [x] Test upgrade and validate all platforms work.
- [x] Debug Linux worker crashes.
- [x] Raise ticket with Unity.
- [x] Implement workaround for C-level dependencies.
- [x] Upgrade to Worker SDK 13.5.1
- [x] Test upgrade again.
- [x] Merge any changes required for the upgrade.
	- [x] `gdk-for-unity` #692 
	- [x] `gdk-for-unity-fps-starter-project` https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/97
	- [x] `gdk-for-unity-blank-project` https://github.com/spatialos/gdk-for-unity-blank-project/pull/20
- [x] Update documentation. #696 
- [x] Release code and publish documentation.

Internal Ticket References: [UTY-1547](https://improbableio.atlassian.net/browse/UTY-1547), [WRK-840](https://improbableio.atlassian.net/browse/WRK-840) (debugging thread)

**Comment by jamiebrynes7** [comment]
### Status Update

Note that we have encountered an issue with Linux workers built with Unity 2018.3.0f2 where they crash due to a `std::bad_cast` exception being thrown. The issue has been traced down to included `libstdc++` symbols and an issue has been raised with Unity.

In the meantime, we have a workaround for our C level dependencies - but this will require the release of the Worker SDK v13.5.1.

**Comment by jamiebrynes7** [comment]
Released in `0.1.4`! 🎉
